# Generated by Django 5.2.12 on 2026-03-09 21:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0004_toolissue_task"),
        ("tasks", "0004_task_completed_at_task_started_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductManufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Название производителя",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Краткая информация о производителе",
                        verbose_name="Описание",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Сайт")),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="Страна"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Производитель товаров",
                "verbose_name_plural": "Производители товаров",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="warehouse.productcategory",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория товара",
                "verbose_name_plural": "Категории товаров",
                "ordering": ["name"],
                "unique_together": {("name", "parent_category")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        help_text="Уникальный артикул товара",
                        max_length=50,
                        unique=True,
                        verbose_name="Артикул",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Текущее количество на складе",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Текущий остаток",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="шт",
                        help_text="шт, м, кг, компл, упак и т.д.",
                        max_length=20,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "min_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="При достижении этого значения рекомендуется заказ",
                        max_digits=10,
                        verbose_name="Минимальный остаток",
                    ),
                ),
                (
                    "max_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Желаемый максимум (для планирования закупок)",
                        max_digits=10,
                        null=True,
                        verbose_name="Максимальный остаток",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Цена за единицу при закупке",
                        max_digits=10,
                        null=True,
                        verbose_name="Закупочная цена",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Цена при списании на задачи",
                        max_digits=10,
                        null=True,
                        verbose_name="Цена списания",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        help_text="Штрихкод товара (EAN-13 и т.п.)",
                        max_length=100,
                        verbose_name="Штрихкод",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/%Y/%m/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Снимать с учёта, если не используется",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлен"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Где товар находится",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouse_products",
                        to="inventory.storagelocation",
                        verbose_name="Место хранения",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="warehouse.productcategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="warehouse.productmanufacturer",
                        verbose_name="Производитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("incoming", "Приход"),
                            ("outgoing", "Расход"),
                            ("write_off", "Списание"),
                            ("inventory", "Инвентаризация"),
                            ("return", "Возврат"),
                        ],
                        max_length=20,
                        verbose_name="Тип движения",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Количество (всегда положительное)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Номер накладной, акта и т.п.",
                        max_length=50,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Причина, особые отметки",
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "old_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Для инвентаризации",
                        max_digits=10,
                        null=True,
                        verbose_name="Старый остаток",
                    ),
                ),
                (
                    "new_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Для инвентаризации",
                        max_digits=10,
                        null=True,
                        verbose_name="Новый остаток",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата операции"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="warehouse.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если расход связан с конкретной задачей",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="tasks.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Движение товара",
                "verbose_name_plural": "Движения товаров",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["article"], name="warehouse_p_article_8df04e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="warehouse_p_name_2938be_idx"),
        ),
    ]
