# Generated by Django 5.2.12 on 2026-03-05 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolManufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: Bosch, Makita, DeWalt",
                        max_length=100,
                        unique=True,
                        verbose_name="Название производителя",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Краткая информация о производителе",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Официальный сайт", verbose_name="Сайт"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Страна производителя",
                        max_length=100,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Производитель",
                "verbose_name_plural": "Производители",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ToolCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: Электроинструмент, Ручной инструмент, Измерительный",
                        max_length=100,
                        unique=True,
                        verbose_name="Название категории",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Краткое описание категории",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategories",
                        to="inventory.toolcategory",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория инструмента",
                "verbose_name_plural": "Категории инструментов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "inventory_number",
                    models.CharField(
                        help_text="Уникальный номер в системе учёта",
                        max_length=50,
                        unique=True,
                        verbose_name="Инвентарный номер",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Заводской номер",
                        max_length=100,
                        verbose_name="Серийный номер",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Доступен"),
                            ("in_use", "Выдан"),
                            ("maintenance", "На обслуживании"),
                            ("write_off", "Списан"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Место хранения"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="Модель инструмента",
                        max_length=100,
                        verbose_name="Модель",
                    ),
                ),
                (
                    "year_of_manufacture",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Год выпуска"
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата приобретения"
                    ),
                ),
                (
                    "purchase_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Стоимость",
                    ),
                ),
                (
                    "condition",
                    models.TextField(
                        blank=True,
                        help_text="Заметки о состоянии, дефектах",
                        verbose_name="Техническое состояние",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="tools/", verbose_name="Фото"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлен"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tools",
                        to="inventory.toolcategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tools",
                        to="inventory.toolmanufacturer",
                        verbose_name="Производитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инструмент",
                "verbose_name_plural": "Инструменты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ToolIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время выдачи"
                    ),
                ),
                (
                    "expected_return_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ожидаемое возвращение"
                    ),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время возврата"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Состояние при выдаче/возврате, особые отметки",
                        verbose_name="Примечания",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tools_issued",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто выдал",
                    ),
                ),
                (
                    "issued_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools_taken",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кому выдан",
                    ),
                ),
                (
                    "returned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tools_received_back",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто принял",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="inventory.tool",
                        verbose_name="Инструмент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выдача инструмента",
                "verbose_name_plural": "Выдачи инструмента",
                "ordering": ["-issued_at"],
            },
        ),
    ]
