# Generated by Django 5.2.12 on 2026-03-05 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: Склад №1, Стеллаж А, Ячейка 12",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Внутренний код или штрихкод места",
                        max_length=50,
                        verbose_name="Код",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация о месте хранения",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("warehouse", "Склад"),
                            ("rack", "Стеллаж"),
                            ("shelf", "Полка"),
                            ("cell", "Ячейка"),
                            ("other", "Другое"),
                        ],
                        default="warehouse",
                        max_length=50,
                        verbose_name="Тип места",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "parent_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Например, ячейка может входить в стеллаж",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sublocations",
                        to="inventory.storagelocation",
                        verbose_name="Входит в",
                    ),
                ),
            ],
            options={
                "verbose_name": "Место хранения",
                "verbose_name_plural": "Места хранения",
                "ordering": ["name"],
                "unique_together": {("name", "parent_location")},
            },
        ),
        migrations.AlterField(
            model_name="tool",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Где инструмент находится",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tools",
                to="inventory.storagelocation",
                verbose_name="Место хранения",
            ),
        ),
    ]
