# Generated by Django 5.2.12 on 2026-03-06 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_storagelocation_alter_tool_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="toolmanufacturer",
            options={
                "ordering": ["name"],
                "verbose_name": "Производитель инструмента",
                "verbose_name_plural": "Производители инструмента",
            },
        ),
        migrations.AlterField(
            model_name="toolcategory",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="toolcategory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название категории"),
        ),
        migrations.AlterField(
            model_name="toolcategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="inventory.toolcategory",
                verbose_name="Родительская категория",
            ),
        ),
        migrations.AlterField(
            model_name="toolmanufacturer",
            name="country",
            field=models.CharField(blank=True, max_length=100, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="toolmanufacturer",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="toolmanufacturer",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название производителя"
            ),
        ),
        migrations.AlterField(
            model_name="toolmanufacturer",
            name="website",
            field=models.URLField(blank=True, verbose_name="Сайт"),
        ),
        migrations.AlterUniqueTogether(
            name="toolcategory",
            unique_together={("name", "parent_category")},
        ),
    ]
