# Generated by Django 5.2.12 on 2026-03-09 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_toolmanufacturer_options_and_more"),
        ("tasks", "0004_task_completed_at_task_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolissue",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tool_issues",
                to="tasks.task",
                verbose_name="Задача",
            ),
        ),
    ]
