# Generated by Django 5.2.12 on 2026-03-04 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="employee",
        ),
        migrations.AddField(
            model_name="task",
            name="co_executors",
            field=models.ManyToManyField(
                blank=True,
                related_name="co_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Соисполнители",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="responsible",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ответственный",
            ),
        ),
    ]
