# Generated by Django 5.2.12 on 2026-03-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_taskstatuslog"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда задача фактически завершена",
                null=True,
                verbose_name="Окончание выполнения",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда задача фактически начата",
                null=True,
                verbose_name="Начало выполнения",
            ),
        ),
    ]
